# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rosetta < Formula
  desc ""
  homepage "https://github.com/userosettadev/rosetta-cli"
  version "0.0.15"

  on_macos do
    url "https://github.com/userosettadev/rosetta-cli/releases/download/v0.0.15/rosetta-cli_0.0.15_darwin_all.tar.gz"
    sha256 "db333b686d3b3a0b505a2f6ee3654c78f1de2a2f622b003f57448865f817a15d"

    def install
      bin.install "rosetta"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/userosettadev/rosetta-cli/releases/download/v0.0.15/rosetta-cli_0.0.15_linux_amd64.tar.gz"
      sha256 "4728c2d191350dce4a8387903a6a86d831a9f7a97cc1402bb84b3e9e2d4d3057"

      def install
        bin.install "rosetta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/userosettadev/rosetta-cli/releases/download/v0.0.15/rosetta-cli_0.0.15_linux_arm64.tar.gz"
      sha256 "ae2e7aecc01e48c723d3d558f23f34d232241078c0622d7488ca687810e0ef86"

      def install
        bin.install "rosetta"
      end
    end
  end
end
