# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rosetta < Formula
  desc ""
  homepage "https://github.com/userosettadev/rosetta-cli"
  version "0.0.21"

  on_macos do
    url "https://github.com/userosettadev/rosetta-cli/releases/download/v0.0.21/rosetta-cli_0.0.21_darwin_all.tar.gz"
    sha256 "b9a14baf86668f86a5936839e588cc979f2986d766edb5be49c0cf9359d606e3"

    def install
      bin.install "rosetta"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/userosettadev/rosetta-cli/releases/download/v0.0.21/rosetta-cli_0.0.21_linux_amd64.tar.gz"
        sha256 "9e634be0888467d8257a70f211f482546c4ce0b7a815b10f3fb8cb1cd3942f8f"

        def install
          bin.install "rosetta"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/userosettadev/rosetta-cli/releases/download/v0.0.21/rosetta-cli_0.0.21_linux_arm64.tar.gz"
        sha256 "0b98aa3e54e63a6e1d6081073a123ad4e41baf67d4ed9778bc055825621a990a"

        def install
          bin.install "rosetta"
        end
      end
    end
  end
end
